version: '3.8'
services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: testDataBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
